version: '3.8'

networks:
  app-network:
    name: stt_save_docker_app-network
    driver: bridge

services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - FAST_REFRESH=false
      - VITE_DEV_SERVER_HOST=0.0.0.0
    networks:
      - app-network
    depends_on:
      - fastapi

  fastapi:
    container_name: modest_khayyam
    build: ./fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    environment:
      - WHISPER_SERVICE_URL=http://whisper:9000
      - TRANSLATION_SERVICE=libre
      - LIBRETRANSLATE_URL=http://libretranslate:5000/translate
    networks:
      - app-network
    depends_on:
      - whisper
      - libretranslate

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=medium
      - ASR_ENGINE=openai_whisper
      - CUDA_VISIBLE_DEVICES=-1
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    networks:
      - app-network

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    command: --load-only th,en,zh,ja,ko,fr,de,es,it,ru
    networks:
      - app-network